name: New Post Update
on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Record push event
        run: echo "New content pushed to posts repository"
